platform:ios,'8.0'
target "HuiKuaiXiuPro"do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'CTAssetsPickerController', '~> 3.3.2-alpha'
pod 'SDWebImage', '~> 4.0.0'
pod 'IQKeyboardManager', '~> 4.0.10'
pod 'WechatOpenSDK'

end
